import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          teal: '#005A64',
          tealLight: '#087E8B',
          tealDark: '#003F46',
          orange: '#F5A623',
          orangeHover: '#E09215',
          sand: '#FBF9F5',
          grayMuted: '#6B7280',
        },
        "surface-container-highest": "#d4e5f1",
        "surface-container-high": "#d9ebf7",
        "tertiary-fixed": "#ffdad2",
        "primary-container": "#087e8b",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001f24",
        "surface-container": "#dff0fd",
        "on-tertiary": "#ffffff",
        "surface-tint": "#006874",
        "outline": "#6e797b",
        "surface-container-lowest": "#ffffff",
        "surface": "#f5faff",
        "surface-dim": "#cbdce8",
        "primary-fixed": "#96f0ff",
        "on-error": "#ffffff",
        "primary": "#00636e",
        "on-secondary-fixed": "#001f24",
        "tertiary-fixed-dim": "#ffb4a2",
        "secondary": "#226771",
        "secondary-fixed": "#adedf9",
        "on-tertiary-container": "#fff7f6",
        "on-primary": "#ffffff",
        "surface-variant": "#d4e5f1",
        "tertiary": "#9e371e",
        "secondary-fixed-dim": "#91d1dc",
        "primary-fixed-dim": "#79d4e2",
        "on-surface-variant": "#3e494a",
        "on-surface": "#0d1d26",
        "inverse-surface": "#22323c",
        "on-secondary-container": "#276b76",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#004f57",
        "inverse-primary": "#79d4e2",
        "surface-container-low": "#e9f5ff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#84250d",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#004f58",
        "on-tertiary-fixed": "#3c0700",
        "background": "#f5faff",
        "on-background": "#0d1d26",
        "on-primary-container": "#eafcff",
        "surface-bright": "#f5faff",
        "tertiary-container": "#bf4f34",
        "outline-variant": "#bdc8ca",
        "inverse-on-surface": "#e2f3ff",
        "secondary-container": "#aaeaf6",
      },
      fontFamily: {
        vietnam: ['"Be Vietnam Pro"', 'sans-serif'],
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      spacing: {
        "gutter": "1.5rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "margin": "2rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "1rem"
      },
      fontSize: {
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "price-display": ["22px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-lg": ["15px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
