packages:
  - "frontend"
  - "backend"
  - "packages/*"
allowBuilds:
  esbuild: true
  prisma: true
  "@prisma/engines": true
  "@embedded-postgres/windows-x64": true
  "@embedded-postgres/linux-x64": true
